-- ====================================================================
-- SUPABASE SCHEMA FOR ORDERS (table: neworders)
-- Run this script in Supabase Dashboard -> SQL Editor
-- ====================================================================

-- 1. Create the orders table
create table if not exists public.neworders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  address text not null,
  product text not null,
  color text,
  quantity integer default 1,
  price numeric default 0,
  shipping_amount numeric default 0,
  total_amount numeric default 0,
  status text default 'pending'
);

-- 2. Create useful index for fast sorting and searching
create index if not exists idx_neworders_created_at on public.neworders (created_at desc);
create index if not exists idx_neworders_status on public.neworders (status);
create index if not exists idx_neworders_phone on public.neworders (phone);

-- 3. Enable Row Level Security (RLS)
alter table public.neworders enable row level security;

-- 4. Create open policy for anon role (landing page and admin direct access)
drop policy if exists "Allow all operations for anon" on public.neworders;

create policy "Allow all operations for anon"
on public.neworders
for all
to anon, authenticated
using (true)
with check (true);
